### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by jaehoonhwang** [jaehoonhwang/CaptsLog#15]
@chet0322 @JeewakaSankalpa @cswezey 
Your pull request is due at **Wednesday Mar 22 by 10 PM**

**Comment by jaehoonhwang** [comment]
@chet0322 @JeewakaSankalpa @cswezey 
When you guys are naming PR, please use following:

`[Category] (#Number) Title`

Example: `[Test](#15) Announcements`

**Categories**:
- [Feature]: Any feature we might add
- [Bug]: Bug fixes
- [Test]: Anything test related

**Number**:
Issue number referencing the pull request.

**Title**:
Brief Description for what pull request is about.

**Comment by chet0322** [comment]
@jaehoonhwang @JeewakaSankalpa @cswezey 
Hey there is a team attendance thing that gets us bonus points for the project starting from next week.

**Comment by jaehoonhwang** [comment]
Okay
