### ISSUE TITLE
[Test] Improve database test coverage

### ISSUE THREAD

**Issue by jaehoonhwang** [jaehoonhwang/CaptsLog#16]
### Problem description
Right now overall coverage sits at 83%.
Let's get it up to 87%.

@JeewakaSankalpa should do it, but if you think you can do it, you are more than welcome to submit a PR.

**Comment by JeewakaSankalpa** [comment]
I'll Work on it

**Comment by jaehoonhwang** [comment]
Create an appropriate pr so nobody works on it.
