### ISSUE TITLE
PyQt Editor

### ISSUE THREAD

**Issue by cswezey** [jaehoonhwang/CaptsLog#24]
Progress:

The basic PyQt editor is complete. It includes a basic built-in GUI with a simple text editor layout and buttons handling basic text formatting functions.

Goals:
1.  Include more PyMarkdown formatting functions and tie them into buttons/keys on the text editor toolbar.

2. Display a live update of the generated HTML from the markdown file.

3. Find a way to test the GUI so that it passes automated tests.

**Comment by jaehoonhwang** [comment]
Closing in reference of#25
