### ISSUE TITLE
[GUI] Display HTML to one of GUI widget

### ISSUE THREAD

**Issue by jaehoonhwang** [jaehoonhwang/CaptsLog#25]
### Problem description

We need to find out a way to display html code that was output by markdown module.

In more detail, have a sample markdown file, then use python and complimentary module to translate markdown file to HTML code and then display it in one of PyQt widget.

From #24 
>Progress:
> The basic PyQt editor is complete. It includes a basic built-in GUI with a simple text editor layout and buttons handling basic text formatting functions.
> Goals:
>Include more PyMarkdown formatting functions and tie them into buttons/keys on the text editor toolbar.
>Display a live update of the generated HTML from the markdown file.
>Find a way to test the GUI so that it passes automated tests.

**Comment by jaehoonhwang** [comment]
What's the status on this @cswezey

**Comment by cswezey** [comment]
I am still working on it. I will have a new pull request with the updated
code ready by tomorrow at 8.
