### ISSUE TITLE
[MISC]DBStatus : Save the Markdown File or Just the text inside Markdown File

### ISSUE THREAD

**Issue by JeewakaSankalpa** [jaehoonhwang/CaptsLog#28]
####
### Save the Markdown File 
* Found a way to save the markdown file without duplication the file.
* If the Markdown Module can create a method for getMarkdownFile() which returns a File object I can work with this method.
### Save only the text inside Markdown File
* Or else i can save just the markdown script inside the database.
* This would be easy to accomplish but also not a good way to do it in my opinion.

**Comment by jaehoonhwang** [comment]
Looks gr8 m8

**Comment by jaehoonhwang** [comment]
Closing this issue: PR #32
